# Generated by Django 5.1.4 on 2026-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mysql_user', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'logs_auditlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
