# Generated by Django 5.1.4 on 2026-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FatigueAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_score', models.FloatField(default=0.0)),
                ('fatigue_score', models.FloatField(default=0.0)),
                ('yawn_count', models.PositiveIntegerField(default=0)),
                ('eyes_closed_secs', models.FloatField(default=0.0)),
                ('result_label', models.CharField(blank=True, choices=[('atento', 'Atento'), ('fatigado', 'Fatigado'), ('distraido', 'Distraido')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analisis de Fatiga',
                'verbose_name_plural': 'Analisis de Fatiga',
                'db_table': 'fatigue_analysis',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
