# Generated by Django 5.1.4 on 2026-03-10 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0002_initial'),
        ('fatigue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fatigueanalysis',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatigue_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatigueanalysis',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_analyses', to='classrooms.student'),
        ),
    ]
