# Generated by Django 5.1.4 on 2026-03-17 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_initial'),
        ('fatigue', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FatigueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatigue_sessions', to='classrooms.classroom')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatigue_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fatigue_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FatigueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('attention_score', models.FloatField(default=0.0)),
                ('fatigue_score', models.FloatField(default=0.0)),
                ('yawn_count', models.PositiveIntegerField(default=0)),
                ('eyes_closed_secs', models.FloatField(default=0.0)),
                ('result_label', models.CharField(blank=True, choices=[('atento', 'Atento'), ('fatigado', 'Fatigado'), ('distraido', 'Distraido')], max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_records', to='classrooms.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fatigue.fatiguesession')),
            ],
            options={
                'db_table': 'fatigue_record',
            },
        ),
        migrations.DeleteModel(
            name='FatigueAnalysis',
        ),
        migrations.AddIndex(
            model_name='fatiguesession',
            index=models.Index(fields=['classroom', 'date'], name='fatigue_ses_classro_f982d0_idx'),
        ),
        migrations.AddIndex(
            model_name='fatiguesession',
            index=models.Index(fields=['maestro', 'status'], name='fatigue_ses_maestro_2a1d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fatiguerecord',
            unique_together={('session', 'student')},
        ),
    ]
