# Generated by Django 5.1.4 on 2026-03-17 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_initial'),
        ('fatigue', '0003_fatiguesession_fatiguerecord_delete_fatigueanalysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualFatigueAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('attention_score', models.FloatField(default=0.0)),
                ('fatigue_score', models.FloatField(default=0.0)),
                ('yawn_count', models.PositiveIntegerField(default=0)),
                ('eyes_closed_secs', models.FloatField(default=0.0)),
                ('result_label', models.CharField(blank=True, choices=[('atento', 'Atento'), ('fatigado', 'Fatigado'), ('distraido', 'Distraido')], max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_fatigue_analyses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_analyses', to='classrooms.student')),
            ],
            options={
                'db_table': 'fatigue_individual_analysis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'date'], name='fatigue_ind_student_ce32a0_idx'), models.Index(fields=['maestro', 'status'], name='fatigue_ind_maestro_252395_idx')],
            },
        ),
    ]
